FORMAT: 1A
HOST: http://dicewa.re/

# diceware

Diceware™ is a method for picking passphrases that uses dice to select words at random from a special list called the Diceware Word List.


## Generating Passphrase [/api/passphrase/?parts={parts}]

+ Parameters
    + parts (number) - number of required passphrase parts

### Getting passphrase [GET]

Getting generated passphrase

+ Response 200 (application/json)

    + Body

            {
                "meta": {
                    "message": "Ok."
                },
                "data": {
                    "passphrase": {
                        "text": "randomgeneratedpasswordexampledude",
                        "parts": [
                            "random",
                            "generated",
                            "password",
                            "example",
                            "dude"
                        ]
                    }
                }
            }

            

+ Response 400 (application/json)

    + Headers

            Location: /api/passphrase/generate/?parts=string

    + Body

            {
                "meta": {
                    "message": "Parts need to be integer in range <1,99>."
                }
            }
